name: Opendata Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: run script
        run: |
          npm install
          npm start
      
      - name: commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status | grep modified && git commit -m "data update(`date +%Y/%m/%d`)" -a || true
          git push
